// <auto-generated />
using System;
using HochschulsportSchichtplan.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HochschulsportSchichtplan.Migrations
{
    [DbContext(typeof(HochschulsportSchichtplanContext))]
    partial class HochschulsportSchichtplanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HochschulsportSchichtplan.Models.Schicht", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Ende");

                    b.Property<string>("Inhaber");

                    b.Property<string>("SchichtName");

                    b.Property<DateTime>("Start");

                    b.Property<double>("Stunden");

                    b.Property<DateTime>("Tag");

                    b.HasKey("Id");

                    b.ToTable("Schicht");
                });
#pragma warning restore 612, 618
        }
    }
}
